#############################################################################
# Makefile for building: test_usensor_rs485_1
# Generated by qmake (2.01a) (Qt 4.8.5) on: Wed May 6 14:52:30 2015
# Project:  test_usensor_rs485_1.pro
# Template: app
# Command: /opt/trik-sdk/sysroots/i686-oesdk-linux/usr/bin/qmake -o Makefile test_usensor_rs485_1.pro
#############################################################################

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -pipe $(OE_QMAKE_CFLAGS) -O2 -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -pipe -pipe $(OE_QMAKE_CFLAGS) $(OE_QMAKE_CXXFLAGS) -O2 -O2 -Wall -W -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++ -I. -I$(OE_QMAKE_INCDIR_QT)/QtCore -I$(OE_QMAKE_INCDIR_QT) -I.
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-rpath-link,$(OE_QMAKE_LIBDIR_QT)
LIBS          = $(SUBLIBS)  -L$(OE_QMAKE_LIBDIR_QT) -lQtCoreE -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
QMAKE         = /opt/trik-sdk/sysroots/i686-oesdk-linux/usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = $(OE_QMAKE_STRIP)
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		test_usensor_rs485_1.pro
QMAKE_TARGET  = test_usensor_rs485_1
DESTDIR       = 
TARGET        = test_usensor_rs485_1

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test_usensor_rs485_1.pro  /opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++/qmake.conf /opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtCoreE.prl
	$(QMAKE) -o Makefile test_usensor_rs485_1.pro
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtCoreE.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile test_usensor_rs485_1.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/test_usensor_rs485_11.0.0 || $(MKDIR) .tmp/test_usensor_rs485_11.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/test_usensor_rs485_11.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/test_usensor_rs485_11.0.0/ && (cd `dirname .tmp/test_usensor_rs485_11.0.0` && $(TAR) test_usensor_rs485_11.0.0.tar test_usensor_rs485_11.0.0 && $(COMPRESS) test_usensor_rs485_11.0.0.tar) && $(MOVE) `dirname .tmp/test_usensor_rs485_11.0.0`/test_usensor_rs485_11.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test_usensor_rs485_11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

